services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - '28017:27017'
    environment:
      # MONGO_INITDB_ROOT_USERNAME:
      # MONGO_INITDB_ROOT_PASSWORD:

    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
